variables: 
    GRADLE_OPTS: "-Dorg.gradle.daemon=false" 

stages:   
    - build 
    - test

build: 
    stage: build 
    script: 
        - cd C:\individual-project-sem3\individual-sem3-backend
        - ./gradlew assemble
    
test: 
    stage: test 
    script: 
        - cd C:\individual-project-sem3\individual-sem3-backend
        - ./gradlew test